<a href="https://colab.research.google.com/github/rohitrmd/pytorch-fundamentals/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello exicted to learn pytorch")

Hello exicted to learn pytorch


resource: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/video_notebooks/00_pytorch_fundamentals_video.ipynb

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


In [4]:
!nvidia-smi

Sun Sep  3 23:28:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Introduction to Tensors
https://pytorch.org/docs/stable/tensors.html


In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8,],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12],[13, 14, 15], [16, 17, 18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([2, 3, 3])

In [19]:
TENSOR[0][1][1]

tensor(5)

### Random Tensors
Why random tensors?
Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [20]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6388, 0.1086, 0.0189, 0.0666],
        [0.2654, 0.7987, 0.4894, 0.4934],
        [0.3486, 0.1797, 0.5819, 0.9483]])

In [21]:
random_tensor.ndim

2

In [22]:
# Let's create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel
random_image_size_tensor.shape


torch.Size([224, 224, 3])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

Creating a range of tensors and tensor-like

In [25]:
one_to_ten = torch.arange(start = 1, end = 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
# float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor


tensor([1., 2., 3.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [30]:
float_16_tensor.dtype

torch.float16

In [31]:
mult = float_16_tensor*float_32_tensor
mult

tensor([1., 4., 9.])

### Getting information from tensors
1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape, use tensor.shape
3. Tensors not on the right device - to get device, use tensor. device

In [32]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4107, 0.3751, 0.1759, 0.9065],
        [0.2437, 0.2073, 0.7432, 0.2890],
        [0.3062, 0.8427, 0.9131, 0.7896]])

In [33]:
# find details of the the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device of tensor: {some_tensor.device}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.4107, 0.3751, 0.1759, 0.9065],
        [0.2437, 0.2073, 0.7432, 0.2890],
        [0.3062, 0.8427, 0.9131, 0.7896]])
Datatype of tensor: torch.float32
Device of tensor: cpu
Shape of tensor: torch.Size([3, 4])


### Manipulating Tensors (tensor operations)
Tensor operatins include:
* Additon
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [34]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Divide by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [38]:
# Try out torch multiply
torch.mul(tensor , 10)

tensor([10, 20, 30])

### Matrix multiplication
Two main ways of performing multiplicatin in neural network
1. Element wise multiplication
2. dot product multiplication



In [39]:
# Element wise multiplication
print(tensor , '*', tensor)
print(f"Equals :{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 141 µs, sys: 24 µs, total: 165 µs
Wall time: 171 µs


tensor(14)

In [43]:
%%time
tensor*tensor

CPU times: user 28 µs, sys: 0 ns, total: 28 µs
Wall time: 31.2 µs


tensor([1, 4, 9])

In [44]:
# Inner dimentions must match
# resulting matrix has shape of outer dimentions
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.5880, 0.4238, 0.2588],
        [0.4882, 0.3620, 0.2282],
        [0.2863, 0.1698, 0.0783]])

# One of the most common errors in deep learning: shape errors

In [45]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
tensor_B = torch.tensor([
    [7, 8],
    [9, 10],
    [11, 12]
])

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

# Finding the min, max, mean, sum, etc

In [46]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [49]:
# mean function - torch.mean() function requires a tensor of float32
torch.mean(x.type(torch.float32))

tensor(45.)

In [50]:
# Find the sum
torch.sum(x)

tensor(450)